# Generated by Django 6.0.7 on 2026-07-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='interest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
