# Generated by Django 6.0.7 on 2026-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_volunteer_email_alter_volunteer_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
